############ server  ############ 
server: 
  port: 9091

############ log ############ 
logging:
  level:
    root: WARN 
    org:
      stockws: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG

########### security ###########
security:
  storeType: JKS
  trustStore: jks/clientTrust.jks
  storepass: clientTrust
  trustKeyAlias: rsaauthKey
  sigAlg: SHA256withRSA
  resourceID: sparklr
  

############ data access ############ 
spring:
  jpa:
    hibernate:
      ddl-auto: none
      packageToScan: org.business.models
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: 
    password: 

############ custom ############     
custom:
  datasource:
    driverClassName: com.mysql.jdbc.Driver