############ redis ############ 
redis:
  host: localhost
  port: 6379
  password: 
  salt: myrosicky@163.com
  
############ solr ############ 
#solr.host=http://localhost:8983/solr/gettingstarted
solr:
  host: http://localhost:8983/solr/db
  home: 

############ SALT ############ 
SALT: LLisMoon
 
############ eureka ############ 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

############ log ############ 
logging:
  path: ./log

############ mq ############ 
mq:
  host: localhost
  port: 5672
  queueName1: LLQUEUE

############ upload ############ 
upload:
  maxUploadSize: 15M
  encoding: UTF-8

############ spring ############ 
spring:
  profiles:
    active: dev
  resources:
    chain:
      cache: false